<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <script>

    //创建Promise
    function MyPromise(fn){
      var self = this;
      this.status = "pending"; //状态
      this.data = "";
      this.error = "";
      // 用于异步操作，存入函数在队列中
      this.onResolveCallbacks = [];
      this.onRejectCallbacks = [];
      function resolve(data){
        if(self.status === "pending"){
          self.status = "resolve";
          self.data = data;
          self.onResolveCallbacks.forEach(fn => fn());
        }
      }
      function reject(err){
        if(self.status === "pending"){
          self.status = "reject";
          self.error = err;
          self.onRejectCallbacks.forEach(fn => fn());
        }
      }
      try{
        fn(resolve, reject);
      }catch(err){
        reject(error);
      }
    }

    MyPromise.prototype.then = function(resolve, reject) {
      var self = this;
      if(self.status === "resolve") {
        // 返回Promise的目的是链式调用
        return new MyPromise((resolve1, reject1) => {
          let res = resolve(self.data);  //这里一定要注意，是resolve，不是resolve1，很容易出错！
          if(res instanceof MyPromise){ //当用户已经返回了Promise时就执行then函数，得到里面的resolve("pppp")或者reject("ooooo")
            res.then(resolve1, reject1);
          }else{
            resolve1(res);
          }
        })
      }else if(self.status === "reject"){
        try{
          return new MyPromise((resolve1, reject1) => {
            let res = reject(self.error);
            if(res instanceof MyPromise){
              res.then(resolve1, reject1);
            }else{
              reject1(res);
            }
          })
        }catch{
          // throw new Error("can`t find reject function");
        }
      }else if(self.status === "pending"){ 
        //处理异步操作，如setTimeout之类的，当进入这里的时候还未进入MyPromise中的resolve和reject
        return new Promise((resolve1, reject1) => {
          // 这里特别重要哟！push(这里面是一个闭包，目的是后面需要resolve函数)
          self.onResolveCallbacks.push((function(resolve){
            return function(){
              let res = resolve(self.data);
              if(res instanceof MyPromise){
                res.then(resolve1, reject1);
              }else{
                resolve1(res);
              }
            }
          }(resolve)))

          self.onRejectCallbacks.push((function(resolve){
            return function(){
              let res = reject(self.error);
              if(res instanceof MyPromise){
                res.then(resolve1, reject1);
              }else{
                reject1(res);
              }
            }
          }(resolve)))

        })
      }
    }
  

    var map = new MyPromise((resolve, reject) => {
      setTimeout(() => {
        resolve(['成功', Math.random()]);
        //reject(['失败', Math.random()]);
      }, 2000)

     //resolve(['成功', Math.random()]);
     //reject(['失败', Math.random()]);
     
    })

    map.then(data => {
      console.log(data);
      return new MyPromise((resolve, reject) => {
        resolve("ppppppp1");
      })
      //return "pppppp"
    }, err => {
      console.log(err);
      // return new MyPromise((resolve, reject) => {
      //   reject("ooooooo");
      // })
      return "oooooooo1";
    })
    .then(data => {
      console.log(data);
      return "ppppppppp2";
    }, err => {
      console.log(err)
      return "ooooooooo2"
    })
    .then(data=>{console.log(data)}, 
    err => { console.log(err) })
    
  </script>
</body>
</html>